### ISSUE TITLE
comment forcer une balance à 0 ?

### ISSUE THREAD

**Issue by fiscafacile** [fiscafacile/CryptoFiscaFacile#15]
**Describe the bug**
J’explique mon besoin : en utilisant la fonction dust_conversion de CDC App, il me reste des poussières de certaines cryptos mais quand je vais sur l’app le solde est de 0.
l’app crop les derniers digits je pense. j’aimerai donc forcer une balance à 0

complément : dans "Amounts" le coin n’apparait pas (donc considéré comme 0 je pense)

**To Reproduce**
Command Line '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Mac/Linux]

**Additional context**

**Comment by fiscafacile** [comment]
Pour commencer l'outil ne fait aucun Arrondi pendant les phases d'agrégation de TXs et de calculs finaux (2086).

Il en fait juste lors des affichages :

- du portefeuille global : il masque les petites balances par défaut, mais il ne les supprime pas pour autant c'est juste un masquage visuel, qui peut d'ailleurs être désactivé avec l'option --exact
- des résultats finaux du 2086 (CLI et XLSX) : les valeurs finales sont arrondis a l'€ prêt comme le demande les impots

**Comment by fiscafacile** [comment]
Ceci dit, le dust-conversion de CdC App est considéré comme des Exchanges avec possiblement plusieurs From de plusieurs coins différents et un seul To en CRO. Mais aucun montant n'est arrondis par l'outil, il se base sur les montants exacts du CSV.

Si l'App crop les derniers digits comme tu le suppose (à confirmer par des screenshot de l'App et de son CSV), on peut y remédier en ajustant les From des coins présents dans des dust_conversions par leur valeur de balance (de la source CdC App uniquement) connus par l'outil, mais cela peut induire des erreurs si l'outil ne connait tout l'historique de la source CdC App (cas d'un CSV tronqué/incomplet/etc...). Donc je vais aussi rajouter une sécurité pour que l'ajustement ne se fasse que dans les "derniers digits" du montant donné par le CSV lors de ce dust_conversion...

**Comment by lebnet** [comment]
Je complète le ticket initial. 

-> CDC App n'a pas l'air d'avoir de problème de crop de digit.

Par contre, la demande reste pertinente de "forcer une balance à 0".

Car par exemple sur Kraken, on peut voir ici ma fiche de stock
![image](https://user-images.githubusercontent.com/7726777/119396325-01d93480-bcd5-11eb-921b-2e9f80286b2b.png)
Il reste une balance de 0,00000461.

Cette balance est confirmée dans l'interface de Kraken
![image](https://user-images.githubusercontent.com/7726777/119396434-1fa69980-bcd5-11eb-80d2-b618a3e512c1.png)

et pourtant le solde affiché est 0,0000
![image](https://user-images.githubusercontent.com/7726777/119396529-3d73fe80-bcd5-11eb-9b10-34dd624f1f62.png)

Il est donc nécessaire de pouvoir forcer la balance à 0.

**Comment by fiscafacile** [comment]
Je pense que tu peux utiliser la fonction SHIT du --txs-categ en recupérant le TX ID de ton retrait du 25/05/2017 et en ajoutant la ligne que voici dans ton fichier CSV qui sera donné a --txs-categ :
`id_de_la_tx_de_retrait,SHIT,Arrondi du solde a 0,0.00000461,LTC`

Je viens de te rajouter la fonction SHIT a Kraken CSV.

Note : pour ce genre de Lost exceptionnel, il est interressant d'utiliser cette methode, plus que celle des Token Delisté
Note2 : du coup le Modifier SHIT pour SHITcoin initialement, devrait plus s'appeler LOST maintenant, a voir si on le renomme
Note3 : il faut bien documenter ces fonctions "Lost" maintenant que l'on a défini leur utilisation
