### ISSUE TITLE
est-ce que tx-display fait un arrondi ?

### ISSUE THREAD

**Issue by fiscafacile** [fiscafacile/CryptoFiscaFacile#16]
**Describe the bug**

**To Reproduce**
Command Line '...'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83117098/119306589-aeca9780-bc6a-11eb-966b-10a10a1f7699.png)
car mon csv et mon fichier de stock indiquent bien -0.09703428

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Mac/Linux]

**Additional context**

**Comment by fiscafacile** [comment]
Non comme stipulé dans #15, l'outil ne fais aucun arrondis, et surtout pas --tx-display.

Par contre le XLSX de stock lui en fait des arrondis (Excel en fait) : 

- il cache les derniers digits si nombre supérieur à un seuil de ton affichage de digit par cellule
- il perd carrément les derniers digits si nombre supérieur à un seuil qu'il ne sait plus gérer, si l'outil tente de lui en donner plus...
- il additionne les Fee/From/Lost dans la même case Sortie (indiscernable dans le stock.xlsx uniquement)

En conclusion : 
- la colonne "Balance" n'est pas toujours égale a la Balance précédente + Entrée - Sortie de la ligne car Excel fait ces arrondis (et l'outil non)
- la fiche de stock n'est pas une vue Exacte alors que les CSV/API sources sont sensés l'être et les --txs-display le sont (basé sur l'état de connaissance des Sources bien sur)

**Comment by fiscafacile** [comment]
peux-tu ajouter une screenshot du CSV et un de la ligne de stock correspondante ?

**Comment by lebnet** [comment]
L'erreur était de mon côté, je me referais aux mauvaises transactions.

Le CSV 
![image](https://user-images.githubusercontent.com/7726777/119397299-38637f00-bcd6-11eb-9e5e-33aead5e4949.png)

La commande 
![image](https://user-images.githubusercontent.com/7726777/119397327-42857d80-bcd6-11eb-9b43-b235259e6ccb.png)
