### ISSUE TITLE
CdC Ex JSON : fees de withdrawal ne sont pas prises en compte

### ISSUE THREAD

**Issue by fiscafacile** [fiscafacile/CryptoFiscaFacile#18]
**Describe the bug**

**To Reproduce**
Command Line '...'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83117098/119307624-4086d480-bc6c-11eb-9d18-299d25dc37cc.png)
après ce retrait ma balance est de 0.1 alors qu’elle devrait être de 0

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Mac/Linux]

**Additional context**

**Comment by lebnet** [comment]
Problème similaire avec Bitstamp. 
ma balance est à 0.001 alors qu'elle devrait être de 0. Par élimination, je tombe sur un withdrawal de Bitstamp

**Comment by fiscafacile** [comment]
artefact d'un autre bug
