### ISSUE TITLE
Binance API : le merge des ordres a l’air de faire des siennes dans certains cas

### ISSUE THREAD

**Issue by fiscafacile** [fiscafacile/CryptoFiscaFacile#20]
**Describe the bug**

**To Reproduce**
Command Line '...'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83117098/119308387-45985380-bc6d-11eb-9529-d0433177e456.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Mac/Linux]

**Additional context**

**Comment by fiscafacile** [comment]
c'est quoi exactement le probleme ? la Note a rallonge ?

**Comment by lebnet** [comment]
d'un côté tu as le CSV qui indique deux transactions 100 + 127 pour un total de 227.
de l'autre côté tu as une seule transaction merged de l'API de 227.

le dedupe ne compare pas les deux (100+127) vs 227 alors que c'est la même et unique transaction.

**Comment by BapRx** [comment]
Salut, c'est pour cette raison que j'ai du supprimer le block qui merge les transactions dans chaque package et ne garder que la dedup globale (voir branche devel de mon fork).

**Comment by fiscafacile** [comment]
Le delta de temps entre 2 trades pour qu'il soit considéré comme du meme Order était de 2 secondes, et dans ton exemple, il y a quasiment 1 minute, c'est pour cela que l'agregation se faisait pas. 

Je viens de passer a 1 minute, mais en ajoutant aussi un check sur les Symbols (pour pas avoir des "To"/"From" hétérogènes).

Mais le problème va revenir quand quelqu'un aura un Order qui sera exécuté sur plus d'une minute... Peut etre qu'il faudra mettre en place une facon manuelle de déclarer plusieurs TX d'un meme Order (avec le --txs-categ)...

**Comment by lebnet** [comment]
Le doublon est toujours présent

![image](https://user-images.githubusercontent.com/7726777/120230602-f6938500-c24f-11eb-9d50-cee0987a1a99.png)
