### ISSUE TITLE
CdC Exchange JSON : problème avec le traitement (dedup)

### ISSUE THREAD

**Issue by fiscafacile** [fiscafacile/CryptoFiscaFacile#23]
**Describe the bug**
Lors du lancement du premier supercharger, je pense que CDC a mal géré le dépôt des récompenses UNI.
Toutes les récompenses quotidiennes du 01/11/2020 au 24/11/2020 ont toute la date identique du 24/11, ce qui fait que lorsqu’il y’a suppression des doublons, ils sont tous supprimés pour ne conserver qu’une seule et unique transaction le 24/11/2020.

**To Reproduce**
Command Line '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/Mac/Linux]

**Additional context**

**Comment by lebnet** [comment]
Complément :

Capture d'écran CDC Exchange
![image](https://user-images.githubusercontent.com/7726777/119397919-1c141200-bcd7-11eb-842c-772e16e9f54e.png)

Capture d'écran Json
![image](https://user-images.githubusercontent.com/7726777/119398229-92187900-bcd7-11eb-9a39-6f21ef5076ab.png)

**Comment by fiscafacile** [comment]
oui, je l'ai fait celui la de SuperCharger donc j'ai noté ces erreurs de date dans le site web de l'exchange. Du coup ca fausse la balance temporairement ce qui me génait pas plus que ca, avant que l'on mette en place la gestion des doublons... Je vais voir comment corriger cela.
