### ISSUE TITLE
Binance api flag provided but not defined error

### ISSUE THREAD

**Issue by arbolis** [fiscafacile/CryptoFiscaFacile#26]
**Describe the bug**
Si j'ai bien compris, je devrais pouvoir obtenir des informations sur mon compte Binance en tappant `./CryptoFiscaFacile --binance-api-key ma_cle_ici --binance-api-secret ma_cle_secrete_ici`. Cependant, cela retourne l'erreur `flag provided but not defined: -binance-api-key`
Ais-je mal compris comment lancer le programme ?

**Desktop (please complete the following information):**
 - OS: Arch Linux.

**Comment by lebnet** [comment]
Il faut désormais directement mettre les paramètres dans le fichier config.yml

**Comment by arbolis** [comment]
Je vous remercie lebnet pour l'information. Je ne trouve pas de fichier en .yml (ni yaml), il y en a-t-il un comme exemple ? Le Readme suggère que oui, il devrait y avoir un fichier exemple à côté de l'exécutable, mais dans mon cas l'exécutable est seul dans son répertoire... désolé pour les questions si basiques...

**Comment by lebnet** [comment]
Oui c'est ce fichier https://github.com/fiscafacile/CryptoFiscaFacile/blob/main/config.example.yml

**Comment by arbolis** [comment]
Ah, merci encore. J'ai donc créé un dossier nommé "Cache" à côté de l'exécutable, j'ai créé le fichier config.yaml (j'ai aussi essayé config.yml). Dans ce fichier il n'y a que ces lignes :

```
exchanges:
  binance:
    account: my_email@adress
    api:
       key: big_thing
       secret: big_secret_thing
```

Ensuite j'exécute l'exécutable en faisant ./CryptoFiscaFacile -stats, et ça retourne 0 EUR instantanément. J'ai commencé à investir sur Binance (et dans les cryptos) en 2021, est-ce que c'est la raison pour laquelle la valeur affichée du portefeuille est nulle ?

**Comment by lebnet** [comment]
Le dossier Cache se crée automatiquement.

Le fichier config.yml se remplit avec tes informations : clé api, api secret et identifiant binance.

Ensuite tu peux relancer.

**Comment by fiscafacile** [comment]
oui, il ne faut pas faire le docssier Cache manuellement, il sera automatiquement géré

par contre le fichier config.yml doit etre a la racine (a coté de l'executable)

tu peux copier config.exemple.yml, puis renommer la copie en config.yml et enfin d'éditer pour le customiser avec tes clé API

Par contre pour revenir a ton premier message, l'erreur "flag provided but not defined: -binance-api-key" veut dire que tu était sur une vielle version du code source, je t'invite a mettre a jour (git pull).

**Comment by arbolis** [comment]
Ah d'accord, merci à vous deux pour ces informations. En fait, j'avais tappé "go get -u github.com/fiscafacile/CryptoFiscaFacile" pour installer le programme. Je n'avais pas "git cloné" le répertoire github. Je vais essayer la démarche.

**Comment by arbolis** [comment]
Ok, j'aurais besoin d'encore un peu d'aide. Donc j'ai git cloné le répertoire, j'ai bien fait une copie du fichier config, puis renommé comme il se doit, toujours dans la racine du répertoire. J'ai rempli les infos que j'ai écrit plus haut. Cependant, il n'y a pas d'exécutable. Donc je tappe la commande du readme "go get -u github.com/fiscafacile/CryptoFiscaFacile", cela télécharge CryptoFiscaFacile v1.1.0, et il y a l'exécutable (mais j'imagine qu'il est basé sur une vieille version de CryptoFiscaFacile...).
J'ai déplacé l'exécutable dans le répertoire que j'avais git cloné, je l'exécute et j'obtiens :


"./CryptoFiscaFacile 
------------------------
| Global Crypto Wallet |
------------------------
Time : 2020-12-31 23:00:00 +0000 UTC
Amounts :
Total Value : 0 EUR
"
J'imagine que c'est parce que mon compte sur Binance a été ouvert en 2021, mais je ne suis pas sûr non plus. Il y a-t-il un moyen de voir si le programme arrive à voir mon solde d'en ce moment ?

**Comment by fiscafacile** [comment]
alors (désolé mais la doc est pas géniale sur ce point) : 
le "go get -u github.com/fiscafacile/CryptoFiscaFacile" va effectivement te compiler que le dernier TAG, alors que l'on a fait beaucoup d'amélioration depuis...
le mieux c'est de faire un "go get" (qui va faire le premier "git clone" normalement) puis d'aller (toujours dans le terminal) dans ton répertoire $GOPATH/src/github.com/fiscafacile/CryptoFiscaFacile, et enfin de faire un "git pull" (ou "git pull origin main" si il couine), puis enfin faire le "go build" pour avoir le binaire a jour sur le dernier code

Désolé c'est pas tres user friendly, mais on bosse plus sur les mecaniques interne que sur le polissage pour l'instant...

**Comment by arbolis** [comment]
Merci beaucoup, je comprends. C'est vraiment sympa de votre part de mettre ce code en open source.
Sur Binance, j'ai limité l'accès à l'API à mon adresse IP. Là ça fait environ 5 minutes que j'ai exécuté CryptoFiscaleFacile et je vois le message "Début de récupération des TXs par l'API Binance (attention ce processus peut être long la première fois)................
".  Le temps d'attente vous semble normal ? Ou alors il y a un problème quelque part ?

**Comment by BapRx** [comment]
Bonjour @arbolis, c'est certainement normal. Tu peux regarder dans le dossier Cache si les données de binance sont bien récupérées.

**Comment by arbolis** [comment]
Merci BapRx! Ce dossier est vide dans mon cas... j'ai attendu une dizaine de minutes avant de stopper l'exécutition. Hmm.
Mon fichier config ne contient que :
```
exchanges:
  binance:
    account: my_email@adress
    api:
       key: big_thing
       secret: big_secret_thing
```

Pour les clés, j'ai essayé les clés directement, avec et sans "". Ca n'a pas fait de différence.

**Comment by BapRx** [comment]
Hmm en effet ce n'est pas normal. Peux-tu activer le début pour voir ce que l'API te répond? `--debug`

**Comment by arbolis** [comment]
Voilà, j'ai modifé la clé de l'api car je préfère ne pas laisser d'information "sensible", mais c'est quasiment le message qui est écrit.
```
Début de récupération des TXs par l'API Binance (attention ce processus peut être long la première fois)...[1/1456] Récupération des trades du symbole ETHBTC
.............2021/05/26 21:05:03.036679 DEBUG RESTY 
==============================================================================
~~~ REQUEST ~~~
GET  /sapi/v1/capital/deposit/hisrec?endTime=1622055902526&recvWindow=60000&signature=....&startTime=1619820000000&status=1&timestamp=1622055902526  HTTP/1.1
HOST   : api.binance.com
HEADERS:
	User-Agent: go-resty/2.6.0 (https://github.com/go-resty/resty)
	X-Mbx-Apikey: ........
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 400 Bad Request
PROTO        : HTTP/2.0
RECEIVED AT  : 2021-05-26T21:05:03.036509552+02:00
TIME DURATION: 509.562439ms
HEADERS      :
	Cache-Control: no-cache, no-store, must-revalidate
	Content-Length: 79
	Content-Security-Policy: default-src 'self'
	Content-Type: application/json;charset=UTF-8
	Date: Wed, 26 May 2021 19:08:39 GMT
	Expires: 0
	Pragma: no-cache
	Server: nginx
	Strict-Transport-Security: max-age=31536000; includeSubdomains
	Via: 1.1 51608619c24847980745d41550b7ad55.cloudfront.net (CloudFront)
	X-Amz-Cf-Id: .........-........-==
	X-Amz-Cf-Pop: LHR61-C1
	X-Cache: Error from cloudfront
	X-Content-Security-Policy: default-src 'self'
	X-Content-Type-Options: nosniff
	X-Frame-Options: SAMEORIGIN
	X-Webkit-Csp: default-src 'self'
	X-Xss-Protection: 1; mode=block
BODY         :
{
   "code": -1021,
   "msg": "Timestamp for this request is outside of the recvWindow."
}
==============================================================================
2021/05/26 21:05:03.036699 DEBUG RESTY 
==============================================================================
~~~ REQUEST ~~~
GET  /api/v3/myTrades?fromId=1&limit=10&recvWindow=60000&signature=.........-........-&symbol=ETHBTC&timestamp=1622055902526  HTTP/1.1
HOST   : api.binance.com
HEADERS:
	User-Agent: go-resty/2.6.0 (https://github.com/go-resty/resty)
	X-Mbx-Apikey: ....
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 400 Bad Request
PROTO        : HTTP/2.0
RECEIVED AT  : 2021-05-26T21:05:03.036526314+02:00
TIME DURATION: 509.930084ms
HEADERS      :
	Cache-Control: no-cache, no-store, must-revalidate
	Content-Length: 79
	Content-Security-Policy: default-src 'self'
	Content-Type: application/json;charset=UTF-8
	Date: Wed, 26 May 2021 19:08:39 GMT
	Expires: 0
	Pragma: no-cache
	Server: nginx
	Strict-Transport-Security: max-age=31536000; includeSubdomains
	Via: 1.1 .........-........-.cloudfront.net (CloudFront)
	X-Amz-Cf-Id: .........-........--bTlqGLXVtuEp8l1MXZTQ==
	X-Amz-Cf-Pop: LHR61-C1
	X-Cache: Error from cloudfront
	X-Content-Security-Policy: default-src 'self'
	X-Content-Type-Options: nosniff
	X-Frame-Options: SAMEORIGIN
	X-Mbx-Used-Weight: 20
	X-Mbx-Used-Weight-1m: 20
	X-Mbx-Uuid: b041ffa5-0f2a-4649-b89c-0d85b6348aa3
	X-Webkit-Csp: default-src 'self'
	X-Xss-Protection: 1; mode=block
BODY         :
{
   "code": -1021,
   "msg": "Timestamp for this request is outside of the recvWindow."
}
==============================================================================
2021/05/26 21:05:03.074243 DEBUG RESTY 
==============================================================================
~~~ REQUEST ~~~
GET  /sapi/v1/capital/withdraw/history?endTime=1622055902526&recvWindow=60000&signature=.........-........-&startTime=1619820000000&status=6&timestamp=1622055902526  HTTP/1.1
HOST   : api.binance.com
HEADERS:
	User-Agent: go-resty/2.6.0 (https://github.com/go-resty/resty)
	X-Mbx-Apikey: .......
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 400 Bad Request
PROTO        : HTTP/2.0
RECEIVED AT  : 2021-05-26T21:05:03.07408542+02:00
TIME DURATION: 547.211222ms
HEADERS      :
	Cache-Control: no-cache, no-store, must-revalidate
	Content-Length: 79
	Content-Security-Policy: default-src 'self'
	Content-Type: application/json;charset=UTF-8
	Date: Wed, 26 May 2021 19:08:39 GMT
	Expires: 0
	Pragma: no-cache
	Server: nginx
	Strict-Transport-Security: max-age=31536000; includeSubdomains
	Via: 1.1 40dd67e1de4ae20a5a592aa54489b7f0.cloudfront.net (CloudFront)
	X-Amz-Cf-Id: ALpm74ljm7E_mcAZjFqCYdnDHrmFyUI8ejo0jixfyzQ1pUCG_x1hxw==
	X-Amz-Cf-Pop: LHR61-C1
	X-Cache: Error from cloudfront
	X-Content-Security-Policy: default-src 'self'
	X-Content-Type-Options: nosniff
	X-Frame-Options: SAMEORIGIN
	X-Webkit-Csp: default-src 'self'
	X-Xss-Protection: 1; mode=block
BODY         :
{
   "code": -1021,
   "msg": "Timestamp for this request is outside of the recvWindow."
}
==============================================================================
2021/05/26 21:05:03.445886 DEBUG RESTY 
==============================================================================
~~~ REQUEST ~~~
GET  /sapi/v1/asset/assetDividend?endTime=1622055902526&limit=500&recvWindow=60000&signature=.........-........-&startTime=1619820000000&timestamp=1622055902526  HTTP/1.1
HOST   : api.binance.com
HEADERS:
	User-Agent: go-resty/2.6.0 (https://github.com/go-resty/resty)
	X-Mbx-Apikey: ........
BODY   :
***** NO CONTENT *****
------------------------------------------------------------------------------
~~~ RESPONSE ~~~
STATUS       : 400 Bad Request
PROTO        : HTTP/2.0
RECEIVED AT  : 2021-05-26T21:05:03.445752667+02:00
TIME DURATION: 919.113205ms
HEADERS      :
	Cache-Control: no-cache, no-store, must-revalidate
	Content-Length: 79
	Content-Security-Policy: default-src 'self'
	Content-Type: application/json;charset=UTF-8
	Date: Wed, 26 May 2021 19:08:39 GMT
	Expires: 0
	Pragma: no-cache
	Server: nginx
	Strict-Transport-Security: max-age=31536000; includeSubdomains
	Via: 1.1 6c973aa0cbaa9809a414d7a4e20e26ce.cloudfront.net (CloudFront)
	X-Amz-Cf-Id: .........-........-lQ==
	X-Amz-Cf-Pop: LHR61-C1
	X-Cache: Error from cloudfront
	X-Content-Security-Policy: default-src 'self'
	X-Content-Type-Options: nosniff
	X-Frame-Options: SAMEORIGIN
	X-Webkit-Csp: default-src 'self'
	X-Xss-Protection: 1; mode=block
BODY         :
{
   "code": -1021,
   "msg": "Timestamp for this request is outside of the recvWindow."
}
==============================================================================

```

**Comment by BapRx** [comment]
Ce message veut dire que le serveur a reçu la requête plus de 60 avant/après le timestamp utilisé lors de la signature de cette requête.
En clair, il y a un décalage trop important entre ton poste et le serveur. Peux-tu vérifier que la date/heure de ton ordi est exacte?

**Comment by arbolis** [comment]
Bien vu... je n'avais jamais remarqué que mon pc avait 4 min de retard !
J'ai relancé le programme, ça prend pas mal de temps, ce n'est pas encore fini pour l'instant et je peux voir le Cache s'agrandir au fur et à mesure. Il y a déjà plus de 1350 fichiers dans le dossier "myTrades".

**Comment by arbolis** [comment]
Ok, je crois que ça marche. Ca me met:
```
| Quantity of TXs By Category |
-------------------------------
Deposits : 0 TXs
Exchanges : 162 TXs
Withdrawals : 0 TXs
------------------------
| Global Crypto Wallet |
------------------------
Time : 2020-12-31 23:00:00 +0000 UTC
Amounts :
Calculating Total native value...Finished
Total Value : 0 EUR
```
Comme je suis perdant pour l'instant, j'imagine que le 0 EUR est normal.

**Comment by BapRx** [comment]
La valeur que tu vois est en date du 31 décembre 2020, tu dis avoir ouvert ton compte en 2021 donc c'est normal que la valeur soit nulle.
Les transactions sont en revanche bien récupérées donc ça devrait être bon !

**Comment by fiscafacile** [comment]
j'ai eu ce meme probleme d'heure du PC desynchro et API inaccessible... je me demande si on devrait pas essayer de cacher cette erreur et afficher quelque chose pour que l'utilisateur sache quoi faire.

**Comment by arbolis** [comment]
Ok parfait merci pour tout ! Je ferme le ticket.
