### ISSUE TITLE
Ajouter les Transfers dans la fiche de stocks

### ISSUE THREAD

**Issue by lebnet** [fiscafacile/CryptoFiscaFacile#27]
**Describe the solution you'd like**
Pouvoir avoir une visibilité sur les transfers (deposits et withdrawals associés) internes dans la fiche de stock. Cela n'inpacte pas la balance mais permet d'avoir un historique complet par coin pour trouver des coquilles.

**Comment by fiscafacile** [comment]
a mon avis c'est deja fait, re-essaye et dis moi

**Comment by lebnet** [comment]
![image](https://user-images.githubusercontent.com/7726777/119553891-598ea300-bd9c-11eb-83bb-13061bc7ca37.png)
C'est ok, merci.
