### ISSUE TITLE
Cafouillage transfers Bittrex vers Crypto.com

### ISSUE THREAD

**Issue by lebnet** [fiscafacile/CryptoFiscaFacile#28]
**Describe the bug**
Les transferts sont démultipliés de Bittrex vers Crypto.com. La balance n'est pas inpactée

**Screenshots**
![image](https://user-images.githubusercontent.com/7726777/119722191-5367f780-be6c-11eb-854d-75030f53c426.png)

**Comment by fiscafacile** [comment]
alors la balance ne semble pas impactée car aucun de ces transferts n'a de frais...

pour ce qui est du cafouillage, je pense que c'est du au fait que tu as fait un virement de Bittrex vers CdC Exchange, puis de CdC Exchange vers CdC App dans un lapse de temps inférieur a 2h avec le même montant (ou presque).

Ca serait pas mal que tu me fournisses les lignes correspondantes dans ton CdC Ex JSON (je te conseille d'utiliser https://jsonformatter.curiousconcept.com/# car dans le json tout est sur une seule ligne) et dans ton CdC App CSV (pour to Bittrex API Cache, je l'ai déjà), comme ca je pourrai reproduire et essayer...

**Comment by lebnet** [comment]
Je pense qu'ils s'agit d'échanges inférieurs à 2h, je t'envoie les sources en privé pour debug. Merci à toi
