### ISSUE TITLE
Lors de l'utilisation du paramètre "delisted-coins", ajouter un commentaire

### ISSUE THREAD

**Issue by lebnet** [fiscafacile/CryptoFiscaFacile#30]
**Is your feature request related to a problem? Please describe.**
Afficher le delisting d'un coin dans le fichier de stock afin de permettre de comprendre visuellement le changement de balance.

**Describe the solution you'd like**
Pour d'avantage de clarté, il serait idéal d'ajouter un commentaire dans la colonne "Note" du fichier excel stock.csv

**Comment by fiscafacile** [comment]
oui c'est pas compliqué ca
