### ISSUE TITLE
Générer un tx id pour les transactions qui n'en ont pas

### ISSUE THREAD

**Issue by lebnet** [fiscafacile/CryptoFiscaFacile#31]
**Is your feature request related to a problem? Please describe.**
Je souhaite arrondir à 0 une balance avec la fonction SHIT, mais la transaction en question n'a pas d'ID donc je ne peux pas agir sur celle-ci

**Describe the solution you'd like**
Générer un tx id pour les transactions qui n'en ont pas. Exemple : Bittrex.

**Additional context**
La transaction en question
![image](https://user-images.githubusercontent.com/7726777/119727946-2ff47b00-be73-11eb-89bf-433bc311cf5c.png)

**Comment by fiscafacile** [comment]
oui c'etait prévu, ben au moins on a un Ticket pour ca maintenant, on risque pas d'oublier ;)

**Comment by lebnet** [comment]
Merci pour le dev de cette feature.

Je pense par contre que l'id n'est pas unique si l'heure est identique. J'ai plusieurs exemples sur bitstamp :
![image](https://user-images.githubusercontent.com/7726777/120976670-d8a7b200-c772-11eb-932a-17bace2fac48.png)
