### ISSUE TITLE
Cerfa 2086 année 2021

### ISSUE THREAD

**Issue by DamienRobert** [fiscafacile/CryptoFiscaFacile#40]
Même si l'année 2021 est loin d'être finie, ça serait bien d'avoir la possibilité d'avoir une preview du Cerfa 2086 des plus et moins values déjà réalisées de l'année 2021. D'après le code c'est actuellement hardcodé dans `CalculatePVMV` de ne montrer que le Cerfa année 2019 et 2020.

**Comment by fiscafacile** [comment]
done
