### ISSUE TITLE
Crash on start `Undefined: New2086` / clarifier comment lancer le script

### ISSUE THREAD

**Issue by gaelj** [fiscafacile/CryptoFiscaFacile#41]
**Describe the bug**
Quand je lance l'application avec `go run main.go`, après l'avoir configurée en suivant le manuel, il crashe directement.
NB: si je lance en debug avec VS code, pas de problème

**To Reproduce**

```
❯ go run ./main.go
# command-line-arguments
./main.go:634:12: undefined: New2086
```

**Expected behavior**
Lancement sans crash...

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - go version go1.16.7 linux/amd64

**Additional context**
J'ai configuré un compte binance et l'emplacement du csv et lancé le programme

**Comment by fiscafacile** [comment]
je viens de tester, tu as raison le "go run main.c" ne suffit pas.

Moi je fais des "go build" en ligne de commande qui créé le fichier binaire executable (exe sous windows), qu'il faut lancer dans un terminal avec les bon arguments.

Le README.md a été mis a jour pour ces détails, cela suffit il ?

**Comment by gaelj** [comment]
J'ai pullé les dernière modifs, en effet le readme est plus clair.
J'ai vu qu'un `make.sh` a été ajouté aussi, par contre il n'est pas executable sous linux, il faut le chmod +x. Comme c'est un flag qui est reconnu par git, je te fais la pull request
